version: "3.8"

services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=stockee'
      - 'MYSQL_USER=myuser4'
      - 'MYSQL_PASSWORD=factoria'
      - 'MYSQL_ROOT_PASSWORD=factoriaf5'
    ports:
      - '7885:3306'
    volumes:
      - stockee-data:/var/lib/mysql

volumes:
  stockee-data:

