spring.application.name=stockee-backend
api-endpoint=/api
spring.profiles.active=${SPRING_PROFILES_ACTIVE:devmysql}
spring.docker.compose.enabled=false
# JWT configuration
jwt.key=${JWT_KEY}

# Email (SMTP) configuration
spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend-url=${FRONTEND_URL:http://localhost:5173}


