spring.application.name=stockee-backend
api-endpoint=/api
spring.profiles.active=devmysql
spring.docker.compose.enabled=true
# JWT configuration
jwt.key=ROBBtQNvcOPwE6kUFc8rPIofcVaixHDYAdZp+re97louCd+ErrlhRIhqLGsXDgOoWUQ+e0X03yh3yMLV3UmXVQ==
