spring.application.name=stockee-backend
api-endpoint=/api
spring.profiles.active=devmysql
spring.docker.compose.enabled=true
# JWT configuration
jwt.key=uLq8WfHj2V1k9p3yQxZ4sM7dR5bN6cA1eF8jG0hT2oQ9rVwXzY+PaSsDfGmHkJtL
